### PR TITLE
change wakelock version from ^0.5.6 to ^0.6.1+1

### PR DESCRIPTION
**Pull request by fehernyul**

### CODE REVIEW

**Comment by Nei1eveN** [comment]
any update on this?

**Comment by diegotori** [comment]
LGTM. Once it passes the automated checks, it should be ready for merging.

**Comment by diegotori** [comment]
@maherjaafar lemme know if you concur. Thanks

**Comment by diegotori** [comment]
@fehernyul looks like format and linting failed. If you're able to, can you please address them? Otherwise, I'll take care of it later today. Thanks.

**Comment by diegotori** [comment]
@fehernyul I have another PR from another contributor that will resolve lint and formatting failures. So this will get merged very shortly.

**Pull request merged**
