### PR TITLE
Feat/casting

### PR DESCRIPTION
**Pull request by 48miles**
adding cast & copy to clipboard button to both Android and iOS default options.

### CODE REVIEW

**Comment by ekuleshov** [comment]
With these changes the example app is crashing a lot on Android 12 device with errors like:

```
D/bonsoir (31569): [66895] Bonsoir failed to start discovery : 4
E/AndroidRuntime(31569): FATAL EXCEPTION: NsdManager
E/AndroidRuntime(31569): Process: com.example.example, PID: 31569
E/AndroidRuntime(31569): java.lang.IllegalArgumentException: listener not registered
E/AndroidRuntime(31569): 	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:59)
E/AndroidRuntime(31569): 	at android.net.nsd.NsdManager.getListenerKey(NsdManager.java:496)
E/AndroidRuntime(31569): 	at android.net.nsd.NsdManager.stopServiceDiscovery(NsdManager.java:636)
E/AndroidRuntime(31569): 	at fr.skyost.bonsoir.discovery.BonsoirDiscoveryListener.dispose(BonsoirDiscoveryListener.kt:167)
E/AndroidRuntime(31569): 	at fr.skyost.bonsoir.discovery.BonsoirDiscoveryListener.dispose$default(BonsoirDiscoveryListener.kt:165)
E/AndroidRuntime(31569): 	at fr.skyost.bonsoir.discovery.BonsoirDiscoveryListener.onStartDiscoveryFailed(BonsoirDiscoveryListener.kt:86)
E/AndroidRuntime(31569): 	at android.net.nsd.NsdManager$ServiceHandler.handleMessage(NsdManager.java:412)
E/AndroidRuntime(31569): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31569): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(31569): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(31569): 	at android.os.HandlerThread.run(HandlerThread.java:67)
I/flutter (31569): [CastDiscoveryService] error PlatformException - PlatformException(discovery_error, Bonsoir failed to start discovery, 4, null)
```

**Comment by diegotori** [comment]
@48miles please re-sync your changes with the latest master changes. Thanks.

**Comment by maherjaafar** [comment]
@48miles This branch has conflicts with the master branch, please resolve it.

**Comment by arodriguezgb** [comment]
Any update on casting?

**Comment by maherjaafar** [comment]
> Any update on casting?

@48miles could you fix the conflicts?

**Comment by Ahmadre** [comment]
> adding cast & copy to clipboard button to both Android and iOS default options.

Very interesting...some people on Github create PR's based on other people's branching they work on 🤔 ...

If you look into the commits you can see that I did the changes and @48miles is not responding...

I will close this PR and re-open, when Casting is properly working. It still has issues.

**Pull request closed without merging**
