### PR TITLE
Add bufferingBuilder

### PR DESCRIPTION
**Pull request by daniellampl**
Add long requested (#80) `bufferingBuilder` for customizing the widget built while chewie buffers the video.

### CODE REVIEW

**Comment by diegotori** [comment]
@daniellampl Thanks for your contribution.

Please re-sync your PR with `master`'s latest changes. Thanks.

**Comment by Ahmadre** [comment]
> Done ✅

Thanks! I try to test this tomorrow after work. Can't promise, but this should be introduced into chewie.

**Review by diegotori — APPROVED** [review]
LGTM.

**Comment by Ahmadre** [comment]
LGTM's too :3 works like a charm. Good job!

**Comment by diegotori** [comment]
Published in version `1.8.4`. Congrats @daniellampl.

**Pull request merged**
